spring:
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: "https://github.com/ferdousulhaque/librarian-config.git"
          label: main
          default-label: main
server:
  port: 8888
